apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: pacman
    server: 'https://kubernetes.default.svc'
  source:
    path: pacman
    repoURL: 'https://github.com/fcarrus/rhacm-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
  sources: []
  project: myproject1
