apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placementrule-prod-cluster
  namespace: policies
spec:
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - prod
  clusterConditions: []
