---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-app-channel
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  type: GitHub
  pathname: https://github.com/fcarrus/rhacm-gitops.git
