# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: pacman-app-acm

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - channel.yaml
#  - policies-config-cm.yaml 
  - subscription.yaml