apiVersion: v1                    
kind: Namespace
metadata:
  name: pacman                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman-app
  namespace: pacman
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - pacman-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: pacman
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: pacman-app
  name: pacman-app-subscription-1
  namespace: pacman
spec:
  channel: rhacm-policies/gitops-demo-policies
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-app-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman-app
  name: pacman-app-placement-1
  namespace: pacman
spec:
  clusterSelector:
    matchLabels:
      'name': 'aws-managed1'