apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-app-subscription
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/pacman-prod  
spec:
  channel: pacman-app-acm/pacman-app-channel
  placement:
    clusterSelector:
      matchLabels:
        'env': 'prod'