apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-app-subscription
  namespace: pacman
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/test  
spec:
  channel: rhacm-policies/pacman-app-channel
  placement:
    local: true